### ISSUE TITLE
cannot assign requested address

### ISSUE THREAD

**Issue by Coachsteveee** [brasfx/Chat_room_multithread_com_sockets#1]
problem with the code execution, can't assign the default address "127.0.0.1"

![image](https://user-images.githubusercontent.com/57384448/103551596-81f92c00-4ee5-11eb-9ed7-aa913f134297.png)

**Comment by brasfx** [comment]
As described in the README, to run the client
<b>Client execution:
1st gcc client.c -o client 
2nd ./client < IP > <server_port>

Example: ./client 127.0.0.1 1234</b>

therefore the word 'localhost' is not valid, it is necessary to enter the address in numeric form.

**Comment by Coachsteveee** [comment]
tried both ways, still same result.
![image](https://user-images.githubusercontent.com/57384448/103556747-2df24580-4eed-11eb-8725-6e35f4c442a8.png)

**Comment by brasfx** [comment]
Are you running the server file before the client? I ran the code now and get it without getting errors.
![image](https://user-images.githubusercontent.com/22081873/103559266-9d881680-4e94-11eb-8380-de11e3cfdbdf.png)
